version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./react-frontend
    container_name: app
    ports:
      - "5173:5173"
    # volumes:
    #   - ./app:/app
    #   - ./tmp:/app/tmp
    # environment:
    #   - RAGFLOW_HOST=ragflow-backend
    #   - RAGFLOW_PORT=8080
    restart: always

  api:
    build:
      dockerfile: Dockerfile
      context: ./taskmanager-api
    container_name: api
    ports:
      - "8080:8080"
    # volumes:
    #   - ./app:/app
    #   - ./tmp:/app/tmp
    # environment:
    #   - RAGFLOW_HOST=ragflow-backend
    #   - RAGFLOW_PORT=8080
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
    ports:
      - "5432:5432"
    volumes:
      - postgres/data:/var/lib/postgresql/data
    restart: always

  # pgadmin:
  #   image: dpage/pgadmin4:8.0
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=my_password
  #   ports:
  #     - "5050:80"
  #   restart: always
