version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./react-frontend
    container_name: app
    ports:
      - "5173:5173"
    volumes:
      - ./react-frontend/src:/app/src
    # environment:
    #   - RAGFLOW_HOST=ragflow-backend
    #   - RAGFLOW_PORT=8080
    restart: on-failure

  api:
    build:
      dockerfile: Dockerfile
      context: ./taskmanager-api
    container_name: api
    ports:
      - "8080:8080"
    # volumes:
    #   - ./app:/app
    #   - ./tmp:/app/tmp
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:postgresql://postgres:5432/postgresdb",
            "spring.datasource.username" : "admin",
            "spring.datasource.password" : "pw",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    restart: on-failure

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pw
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=my_password
    ports:
      - "5050:80"
    restart: on-failure
